== Introduction

=== STEP ISO-10303

PIComposer is a STEP ISO-10303 Standard document editor powered by a highly performant EXPRESS document store. To support real-time applications, the document store utilizes its own lossless proprietary binary encoding of EXPRESS data.

Furthermore, to handle models that may not fit into device memory, PIComposer lazy loads all data on demand. EXPRESS models and their entity instances (referred to as instances) are accurately presented in its user interface as trees and directed acyclic graphs.

As a user, it is best to think of PIComposer Community Edition as Excel for BIM, with the difference being that instead of interacting with sheets, rows, columns, and cells, a user works with trees and tree nodes. By utilizing the spatial tree and entity instance detail tree, PIComposer users can interact directly with BIM models. Authoring a BIM model involves adding tree nodes and updating tree node values. Upon each user interaction, SchemaSense, PIComposer's schema-aware intelligent agent, is active, providing user guidance and a context-sensitive set of menu commands on each node. There are three trees in PIComposer:

* The spatial tree that manages the model spatial structure
* The placement tree, which is responsible for instance placement
* The instance detail tree, which manages instance attributes.

Most of the user's work involves using the tools and commands of PIComposer to manipulate the above trees.

[NOTE]
====
PIComposer Community Edition is capable of handling any STEP AP through its document store. However, in the context of the community edition, it is specifically restricted to a version of IFC: https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/[*ifc4x3*]. For the remainder of this document, our discussion will focus specifically on IFC.
====

[WARNING]
====
A user of PIComposer Community Edition is assumed to have some knowledge of, or at least a desire to learn, https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/[*IFC*]. This is because PIComposer manipulates IFC models by providing user interfaces that directly interact with the content of IFC models, including entities, selects, enums, and more. Without an understanding of IFC, both this document and the PIComposer application itself may be difficult to comprehend. 
====

=== Data Storage and Organization

A user's data is organized within a workspace. A workspace consists of multiple projects owned by the user. Each project is composed of many documents.

Most of the storage in PIComposer is consumed by the documents. There are various types of documents, including templates, scripts, and BIM models.

Within a BIM model, the majority of the storage is devoted to entity instances. Additionally, a model document also stores entity instance's inverse attributes, tags, search indices, and other supplemental data.

Conceptually, models are documents in a project. However, each BIM model is a document database where documents are stored as binary buffers. These buffers store entity instances. Unlike a line in an ISO-10303 part 21 model file or an element of a typed dataset in part 26 (HDF5 binary encoding), a binary buffer typically contains a logically grouped set of entity instances. Furthermore, if an attribute of an entity instance is itself an entity type, it might be recursively composed within the owning entity instance.

That is, using part 21 and IFCPERSONANDORGANIZATION entity as an illustration, instead of storing instances as:
[source,javascript]
----
#1=IFCPERSON($,'John','Doe',$,$,$,$,$);
#2=IFCORGANIZATION($,'Procedural Information System, LLC',$,$,$);
#3=IFCPERSONANDORGANIZATION(#1,#2,$);
----

structually, a buffer might alternatively store IFCPERSONANDORGANIZATION as:

[source,javascript]
----
#3=IFCPERSONANDORGANIZATION(#1=IFCPERSON($,'John','Doe',$,$,$,$,$),#2=IFCORGANIZATION($,'Procedural Information System, LLC',$,$,$),$);
----

Storing the buffer in the latter structure has many benefits, including:

* better overall compression
* reduced number of disk read/write operations
* reduced number of database queries
* structure simplicity and easily managed data consistency

[NOTE]
====
The PIComposer command to create the first IFCPERSONANDORGANIZATION structure is <<node_commands,set reference>> command, the second is the <<node_commands,create>> command.  Which structure to prefer depends on whether the  entity instance stored in an attribute should be shared.
====

[NOTE]
====
PIComposer stores STRING types using utf8 encoding.
====

PIComposer organizes BIM model data similar to an Entity Component System https://en.wikipedia.org/wiki/Entity_component_system[*(ECS)*]. 

.Entity Component System
[sidebar]
--
In a typical ECS system:

* an entity is a object with a unique identifier
* a component is entity's associated data
* a system is the logic operating on entities and their components.
--

The central elments in a BIM model are instances of a non-abstract IfcProduct subtype; these instances usually appears in the spatial tree. Each of these instance has an immutable 64-bit integer identifier and plays the entity role in a ECS system.

A component is a special type of instance that is a container of a set of IFC instances; it is composition and aggregation of a set of logically related IFC instances.  These components include shapes, propertysets, local placement, and a few other types.

[NOTE]
====
A component could be associated to instance either using an instance's attribute or through a relationship object.
====

.placement component example
[example]
====
A placement component is a IfcLocalPlacement instance comprises of axis instances, position instance, etc. All the data that would completely define IfcLocalPlacement are placed in a single store document.
And the placement is associated to an instance using the IfcProduct's ObjectPlacement attribute.
====

[TIP]
====
Only non-abstract entity types could be instantiated as instance.  
====

Currently, a component must be of the following type:

* IfcShapeRepresentation (shape)
* IfcLocalPlacement (placement)
* IfcRelDefinedByType (type)
* IfcRelDefinedByProperties (propertyset, quantityset)
* IfcPresentationLayerAssignment (layer)
* IfcRelAssociatesMaterial (material)
* Spatial relationship entities:
** IfcRelAggregates
** IfcRelContainedInSpatialStructure
** Other subtype of IfcRelationship

In addition to instances and components, other concrete IFC types could be instantiated into the model as free form instance and will be stored as a document.
A good example of such an instance is instance of IfcOwnerHistory.

=== Templates

Most BIM modeling tasks in PIComposer, such as creating a model or modeling real-world objects like tables, can be easily accomplished using templates. Templates are a fundamental mechanism for users to configure, enhance, or customize PIComposer.

At its core, a template is a set of pre-programmed instructions to be executed by PIComposer, written in either Dart, C++, or JSON. PIComposer supports multiple types of templates, including:

* spatial template
* instance template
** (simple) template 
** parametric template
** transform
** procedural entity
* propertyset template
* quantityset template
* enum template

A spatial template allows users to scaffold an IFC model during the initial creation phase. It defines the initial spatial structure of the model, such as the site, the number of IfcBuildings, and IfcBuildingStoreys. Additionally, a spatial template specifies the relative placement of each spatial element.

Spatial templates are authored using JSON.

When a spatial template is executed, a model is created with a root IfcProject and all the spatial elements specified in the JSON file. The execution also includes the relevant context information, such as the model's unit system.

In PIComposer, distance measurements are in millimeters, and angle measurements are in radians. Property and quantity values conform to the MKS unit measure system. This convention establishes an implicit context for templates.

Instance templates serve as instance factories, simplifying the creation of instances within a model. There are four different types of instance templates (as mentioned above), and the instances created by these templates must be of the IfcShapeRepresentation type or a subtype of IfcProduct. 

[NOTE]
====
A template could be private to a user's project or be shared in the cloud and be available for all PIComposer users.
====

A simple template is an extracted representation of a component or instance within the scope of a project. It can be easily reinstantiated in any other model within the same project. Simple templates serve as a basic form of reuse in PIComposer, enabling copy and paste functionality across spaces and time. If the template represents an IfcProduct, it includes the associated shape of the instance.

A parametric template is a simple template that exposes its attriubute and composite instances and their attributes to direct user manipulation. We called the exposed attributes parametrized attributes. The parametrized attributes are configured using JSON.

A transform template is a parametric template that incorporates an associated procedure. This procedure can take a simple template as input and produce a more complex output. PIComposer includes multiple examples of parametric templates, such as a transformation that takes a BREP box as input and generates a frustum as output.

Procedural entity templates are creational procedures that instantiate instances. They are dart or C++ script with a json configuration file. The configuration file specifies the user input parameter and script input parameters. PIComposer provides several examples of procedural entity templates.

Since not all propertyset and quantityset are published within the ifc schema EXPRESS file, these missing https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-b/alphabeticalorder_psets.htm[*propertyset*], https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-b/alphabeticalorder_qsets.htm[*quantityset*], plus user definded propertyset must be configured using templates so that PIComposer could properly instantiate them. These templates are json files. Many examples are provided with the PIComposer release.

=== Filters

The https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/[*ifc4x3*] schema has 130 https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-b/alphabeticalorder_definedtypes.htm[*defined types*], more than 240 https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-b/alphabeticalorder_enumtypes.htm[*enum types*], almost 100 https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-b/alphabeticalorder_selecttypes.htm[*select types*], and more than 800 https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-b/alphabeticalorder_entities.htm[*entity types*].  In a typical IFC office tower model, it is common to have tens of million of entity instances.  To analyze and dissect this massive volume and variety of BIM data set, PIComposer provides a multitude of filters.  

In a model, instances could be filtered by:

* instance type
* instance id and range
* tag (instance could be tagged and searched)
* layer

Templates could be filtered by: type and tag. 

=== 3d Viewer

IFC models are 3d datasets. For the community edition, PIComposer 3d view is provided via integration with web-ifc-viewer from the https://ifcjs.github.io/info/[*Ifc.js project*].

The source code for the integration is open source, source code is https://github.com/chi-w-ng/picomposer_community_edition[here].

=== Support and Bug reporting

To report an issue or request a feature please go to this project's github portal: https://github.com/chi-w-ng/picomposer_community_edition[picomposer_community_edition] and create an issue.











   